### ISSUE TITLE
Support for CL-RSA

### ISSUE THREAD

**Issue by eadventurous** [hyperledger/ursa#135]
In the README [supported signatures](https://github.com/hyperledger/ursa#supported-signatures) section it is mentioned that Camenisch Lysyanskaya RSA based signatures are supported. But in the documentation of the latest version [there is no module](https://docs.rs/ursa/0.3.4/ursa/signatures/index.html) for this type of signatures, so from what I understand it is still in development.

It would be great if you will mention the status of the CL_RSA in the readme - `in development` or something like this.

**Comment by mikelodder7** [comment]
It’s in the folder named cl. See https://github.com/hyperledger/ursa/tree/master/libursa/src/cl

**Comment by mikelodder7** [comment]
It’s being actively used by Hyperledger Indy, Sovrin, and others

**Comment by eadventurous** [comment]
Thanks!
