### ISSUE TITLE
[Feature]: Go-callable library interface

### ISSUE THREAD

**Issue by davidkhala** [hyperledger/ursa#139]
> @mikelodder7
> Now that we have `C-callable library interface`, how about we go a step further with help of `CGO` to provide golang one?

That would be great. We accept PRs.

_Originally posted by @brentzundel in https://github.com/hyperledger/ursa/issues/133#issuecomment-676426155_

**Comment by brentzundel** [comment]
closing, https://github.com/hyperledger/ursa-wrapper-go now exists.
