### ISSUE TITLE
Unable to import ursa library

### ISSUE THREAD

**Issue by arunprakashpj** [hyperledger/ursa#160]
I am trying to execute Hyperledger Ursa(https://github.com/hyperledger/ursa) as described in  https://crates.io/crates/ursa. That is , I have added the ursa as dependency in Cargo.toml. Then i just imported it as below

extern crate ferris_says;
extern crate ursa;

use ferris_says::say;
use std::io::{ stdout, BufWriter };
use ursa::bls::*;

fn main() {
let out = b"Hello fellow Rustaceans!";
let width = 24;

let mut writer = BufWriter::new(stdout());
say(out, width, &mut writer).unwrap();
}

But the system is throwing err as , the ursa cannot be compiled.  If ferris_says can work properly, why not ursa ?

**Comment by mikelodder7** [comment]
What version of Rust are you using? Make sure you are on the latest version.

**Comment by arunprakashpj** [comment]
I am using Rust 1.43.0

**Comment by arunprakashpj** [comment]
> What version of Rust are you using? Make sure you are on the latest version.

I am using Rust 1.43.0

**Comment by mikelodder7** [comment]
Try running `rustup update` to 1.47.0

**Comment by arunprakashpj** [comment]
> Try running `rustup update` to 1.47.0

Thanks @mikelodder7 ! Perfect !
