### ISSUE TITLE
Remove Xenial

### ISSUE THREAD

**Issue by dcmiddle** [hyperledger/ursa#164]
We have convenience containers for build environments for various OS's. 
Xenial (Ubuntu 2016 LTS) is pretty old at this point and I would like to remove it.
If you are actively using that container and for some reason can't use a newer option please comment in this issue.

**Comment by brentzundel** [comment]
Hyperledger Indy's Plenum and Node packages still only run on Ubuntu 16

**Comment by dcmiddle** [comment]
> Hyperledger Indy's Plenum and Node packages still only run on Ubuntu 16

Ok I'm fine leaving it up then.
I've updated all the ubuntu ('16, '18, '20) here: https://github.com/hyperledger/ursa/pull/166
