### ISSUE TITLE
Resease a new version with updated ed25519-dalek

### ISSUE THREAD

**Issue by askolesov** [hyperledger/ursa#178]
We have a dependency collision with `cosmos_sdk=0.1.1` crate in our project.

```
error: failed to select a version for `ed25519-dalek`.
    ... required by package `tendermint v0.19.0`
    ... which is depended on by `cosmos_sdk v0.1.1`
    ... which is depended on by `libindy v1.95.0 (.../libindy)`
versions that meet the requirements `^1` are: 1.0.1, 1.0.0

all possible versions conflict with previously selected packages.

  previously selected package `ed25519-dalek v1.0.0-pre.3`
    ... which is depended on by `ursa v0.3.5`
    ... which is depended on by `libindy v1.95.0 (.../libindy)`

failed to select a version for `ed25519-dalek` which could resolve this conflict
```

The version of `ed25519-dalek` is already updated in master. Could you please publish it to crates.io?

**Comment by ryjones** [comment]
Does this help? #179

**Comment by askolesov** [comment]
Unfortunately, no(

* The version of `ed25519-dalek` in the master was already compatible with the crate we use.
* It wasn't (and isn't) published to crates.io so we can consume it.
* Rust can consume git repositories as dependencies but we can't use this feature either because there are two crates called `lindy` in the repository: one is in the root, the other one is in `/libindy`. Rust takes the wrong crate and there is no way to resolve this collision.

So all necessary changes are done but we can consume it neither in crates.io nor in git. Could you please publish the updated version to crates.io?

**Comment by mikelodder7** [comment]
Published

**Comment by askolesov** [comment]
Thanks a lot!

**Comment by ryjones** [comment]
Mike Lodder published a new release: https://crates.io/crates/ursa/versions
