### ISSUE TITLE
Publish the new version to crates.io

### ISSUE THREAD

**Issue by askolesov** [hyperledger/ursa#189]
@ryjones @mikelodder7 Could you please publish the new version to crates.io? It would help us a lot.

**Comment by ryjones** [comment]
should I wait for #190 to get merged?

**Comment by askolesov** [comment]
Yes please

**Comment by askolesov** [comment]
@ryjones Could you please ask someone to approve it?

**Comment by ryjones** [comment]
@askolesov I asked in [chat](https://chat.hyperledger.org/channel/ursa?msg=aFm37rRHgWL4b2C4g)

**Comment by ryjones** [comment]
@askolesov is #186 also needed?

**Comment by askolesov** [comment]
We've already bumped `k256` [here](https://github.com/hyperledger/ursa/pull/188). `p256` doesn't introduce conflicts for us so I suggest publishing the new version now.

**Comment by askolesov** [comment]
@ryjones  Thanks for creating a GitHub release! Can this be also pushed in crates.io?

**Comment by ryjones** [comment]
@askolesov I have tried to set up an action to publish, but it doesn't work like I expect. Could you help me over here? https://github.com/ryjones/ursa/commit/e90c24b9f1769defb752dbaefdf76449ab66d949 once the action will do a `--dry-run` successfully then I will move it over here

**Comment by askolesov** [comment]
Sure I tried to build a package with @Artemkaaas today but it fails with strange errors. We think they were in the previous release as well. @mikelodder7 could you please help us?

**Comment by brentzundel** [comment]
@askolesov what are the errors? Could you paste them here?

**Comment by ryjones** [comment]
@brentzundel check out over here: https://github.com/ryjones/ursa/commit/2eaa468f92c8505f8472ed5f36dfbc120302e425#diff-9efc738000935f7d55626940aa06fd013cffe8779f5169b16b50e98331612aa0R3

**Comment by ryjones** [comment]
@askolesov I think Mike Lodder published it two days ago - confirm?

**Comment by askolesov** [comment]
Yes, thanks a lot!
