### ISSUE TITLE
Master Secret (or Link Secret) in anoncreds_demo

### ISSUE THREAD

**Issue by BruceChen1995** [hyperledger/ursa#202]
I drew a diagram based on the [anoncreds_demo](https://github.com/hyperledger/ursa/blob/ece6ce32a59df4e1f99fa38243c1236423066bc2/libursa/tests/cl.rs#L29) to figure out how to use ursa, but I'm not sure if the issuer will/should know the master secret. According to [Indy SDK doc](https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/how-tos/issue-credential/README.html#step-3) and the demo, a master secret is a special piece of data that’s inserted into a credential in blinded form and is given to issuer directly in plaintext.
![anoncreds_demo](https://user-images.githubusercontent.com/39727212/156971954-4c882ea0-2220-4cea-a617-67a3be3ecfc4.png)

**Comment by brentzundel** [comment]
The link secret is known only to the Prover. A blinded commitment to the link secret is provided to the Issuer for inclusion into the credential signature.
